version: "3.2"

services:
  dev:
    container_name: substrate-task-auction
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/substrate-task-auction
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/substrate-task-auction/.cargo
    volumes:
      - .:/var/www/substrate-task-auction
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/substrate-task-auction --dev --ws-external"
